### ISSUE TITLE
Cluster render in wrong location

### ISSUE THREAD

**Issue by jdayus** [SoftwareAG/cumulocity-data-points-map-widget-plugin#1]
![image](https://github.com/SoftwareAG/cumulocity-data-points-map-widget-plugin/assets/94570594/7ce364de-29ae-4222-ba8b-1275d541ee26)

All clusters should be aligned to the actual asset locations.  

Ideally, the map would be zoomed into to show all asset clusters and not display the entire globe.  Furthermore, when zooming, the map should stay centered on asset clusters displayed.

**Comment by DarpanLalani** [comment]
working fine with 1.1
